alias: BIG 3 - Google Kalender
description: ""
triggers:
  - trigger: time_pattern
    hours: "1"
conditions: []
actions:
  - alias: Get events 0 day(s) from now
    data:
      start_date_time: "{{ today_at('00:00') }}"
      end_date_time: "{{today_at('00:00') + timedelta(days=1)}}"
    response_variable: cal_day_0
    target:
      entity_id:
        - calendar.YOURGOOGLECALENDAR
    action: calendar.get_events
  - alias: Get events 1 day(s) from now
    data:
      start_date_time: "{{ today_at('00:00') + timedelta(days=1) }}"
      end_date_time: "{{ today_at('00:00') + timedelta(days=2) }}"
    response_variable: cal_day_1
    target:
      entity_id:
        - calendar.YOURGOOGLECALENDAR
    action: calendar.get_events
  - alias: Get events 2 day(s) from now
    data:
      start_date_time: "{{ today_at('00:00') + timedelta(days=2) }}"
      end_date_time: "{{ today_at('00:00') + timedelta(days=3) }}"
    response_variable: cal_day_2
    target:
      entity_id:
        - calendar.YOURGOOGLECALENDAR
    action: calendar.get_events
  - alias: Get events 4 day(s) from now
    data:
      start_date_time: "{{ today_at('00:00') + timedelta(days=3) }}"
      end_date_time: "{{ today_at('00:00') + timedelta(days=4) }}"
    response_variable: cal_day_3
    target:
      entity_id:
        - calendar.YOURGOOGLECALENDAR
    action: calendar.get_events
  - alias: Extract events from all calendars
    variables:
      events_day0: >
        {{ cal_day_0.values() | map(attribute='events') | list |
        sum(start=[])}} 
      events_day1: >
        {{ cal_day_1.values() | map(attribute='events') | list |
        sum(start=[])}} 
      events_day2: >
        {{ cal_day_2.values() | map(attribute='events') | list |
        sum(start=[])}} 
      events_day3: >
        {{ cal_day_3.values() | map(attribute='events') | list |
        sum(start=[])}} 
      count0: |
        {% if (events_day0 | count == 0) %}
          1
        {% else %}
          {{ events_day0 | count }}
        {% endif %}
      count1: |
        {% if (events_day1 | count == 0) %}
          1
        {% else %}
          {{ events_day1 | count }}
        {% endif %}
      count2: |
        {% if (events_day2 | count == 0) %}
          1
        {% else %}
          {{ events_day2 | count }}
        {% endif %}
      count3: |
        {% if (events_day3 | count == 0) %}
          1
        {% else %}
          {{ events_day3 | count }}
        {% endif %}
      gap_header: 5
      gap_line: 1
      gap_days: 1
      gap_title: 10
      gap_text: 16
      days:
        - Montag
        - Dienstag
        - Mittwoch
        - Donnerstag
        - Freitag
        - Samstag
        - Sonntag
      months:
        - Januar
        - Februar
        - März
        - April
        - Mai
        - Juni
        - Juli
        - August
        - September
        - Oktober
        - November
        - Dezember
  - alias: Send generated Agenda to OEPL
    metadata: {}
    data:
      rotate: 0
      dry-run: false
      payload:
        - type: icon
          value: >
            {% set state = states('sensor.pirate_weather_daily') %} {% if state
            == 'clear-night' %}
              mdi:weather-night
            {% elif state == 'cloudy' %}
              mdi:weather-cloudy
            {% elif state == 'fog' %}
              mdi:weather-fog
            {% elif state == 'hail' %}
              mdi:weather-hail
            {% elif state == 'lightning' %}
              mdi:weather-lightning
            {% elif state == 'lightning-rainy' %}
              mdi:weather-lightning-rainy
            {% elif state == 'partlycloudy' %}
              mdi:weather-partly-cloudy
            {% elif state == 'pouring' %}
              mdi:weather-pouring
            {% elif state == 'rainy' %}
              mdi:weather-rainy
            {% elif state == 'snowy' %}
              mdi:weather-snowy
            {% elif state == 'snowy-rainy' %}
              mdi:weather-snowy-rainy
            {% elif state == 'sunny' %}
              mdi:weather-sunny
            {% elif state == 'windy' %}
              mdi:weather-windy
            {% elif state == 'windy-variant' %}
              mdi:weather-windy-variant
            {% else %}
              mdi:weather-cloudy
            {% endif %}
          x: 40
          "y": 27
          size: 50
          color: black
        - type: text
          value: YOUR HOMETOWN
          x: >
            {% set col_width = 130 %} {% set char_width = 11 %}  {# Je nach Font
            und Größe anpassen! #} {% set text = "YOUR HOMETOWN" %} {{ ((col_width -
            (text|length * char_width)) // 2) }}
          "y": 7
          size: 16
          font: ../../media/Bungee.ttf
        - type: text
          value: >-
            {{ state_attr('sensor.pirate_weather_daily',
            'forecast')[0].temperature }}°C
          x: 15
          "y": 85
          size: 20
        - type: text
          value: >-
            {{ state_attr('sensor.pirate_weather_daily', 'forecast')[0].templow
            }}°C
          x: 15
          "y": 105
          size: 16
        - type: text
          value: >-
            {{ state_attr('sensor.pirate_weather_daily',
            'forecast')[0].precipitation_probability | round(0) }}%
          x: 90
          "y": 105
          size: 16
        - type: icon
          value: mdi:weather-rainy
          x: 90
          "y": 85
          size: 16
        - type: text
          value: "{{ as_timestamp(now()) | timestamp_custom('%d%m%H%M') }}"
          x: 332
          "y": 2
          size: 10
          font: ../../media/GothamRnd_Bold.ttf
        - type: icon
          value: mdi:sofa
          x: 15
          "y": 130
          size: 30
        - type: text
          value: "{{ states('SENSOR.LIVINGROOMTEMPERATURE') | int }}°C"
          x: 10
          "y": 164
          size: 16
        - type: icon
          value: mdi:home-export-outline
          x: 80
          "y": 130
          size: 30
        - type: line
          x_start: 63
          x_end: 63
          y_start: 130
          y_end: 180
          width: 1
          fill: black
        - type: text
          value: "{{ states('SENSOR.OUTDOORTEMPERATURE') | int }}°C"
          x: 80
          "y": 164
          size: 16
        - type: line
          x_start: 5
          x_end: 125
          y_start: 125
          y_end: 125
          width: 1
          fill: black
        - type: line
          x_start: 130
          x_end: 130
          y_start: 5
          y_end: 180
          width: 1
          dashed: false
          fill: black
        - type: text
          value: >-
            {{ days[today_at('00:00').weekday()] }} {{ today_at('00:00').day }}.
            {{ months[today_at('00:00').month-1] }} 
          font: ../../media/Bungee.ttf
          x: 140
          "y": |
            {{ gap_header + 2.5 * gap_line}}
          size: 16
          color: black
        - type: multiline
          value: |
            {% if events_day0 | count > 0 %}
              {% for event in (events_day0 | sort(attribute='start') | list) -%} 
                {% if as_timestamp(event.start) | timestamp_custom('%H:%M') == "00:00"%}
                  #Ganztägig - {{ event.summary }}
                {% else %}
                  #{% if as_timestamp(event.start) | timestamp_custom('%d%m%y') != as_timestamp(event.end) | timestamp_custom('%d%m%y') %}{{ days[(as_timestamp(event.start) | timestamp_custom('%w') | int)-1][:3] }} {% endif %}{{as_timestamp(event.start) | timestamp_custom('%H:%M') }} - {% if as_timestamp(event.start) | timestamp_custom('%d%m%y') != as_timestamp(event.end) | timestamp_custom('%d%m%y') %}{{ days[(as_timestamp(event.end) | timestamp_custom('%w') | int)-1][:3] }}{% endif %} {{as_timestamp(event.end) | timestamp_custom('%H:%M') }}: {{ event.summary }}
                {% endif -%}
              {% endfor -%}
            {% else %}
              #Ingenting
            {% endif -%}
          font: ../../media/Abel-Regular.ttf
          start_y: |
            {{ gap_header + gap_title + 0 * gap_line}}
          delimiter: "#"
          size: 16
          offset_y: 16
          x: 140
        - type: text
          value: >-
            {{ days[(today_at('00:00')+ timedelta(days=1)).weekday()] }} {{
            (today_at('00:00') + timedelta(days=1)).day }}. {{
            months[(today_at('00:00')+ timedelta(days=1)).month-1] }}
          font: ../../media/Bungee.ttf
          x: 140
          "y": |
            {{ gap_header + gap_title + gap_days + ((count0 + 1) * gap_text)}}
          size: 16
          color: black
        - type: multiline
          value: |
            {% if events_day1 | count > 0 %}
              {% for event in (events_day1 | sort(attribute='start') | list) -%} 
                {% if as_timestamp(event.start) | timestamp_custom('%H:%M') == "00:00"%}
                  #Ganztägig - {{ event.summary }}
                {% else %}
                  #{% if as_timestamp(event.start) | timestamp_custom('%d%m%y') != as_timestamp(event.end) | timestamp_custom('%d%m%y') %}{{ days[(as_timestamp(event.start) | timestamp_custom('%w') | int)-1][:3] }} {% endif %}{{as_timestamp(event.start) | timestamp_custom('%H:%M') }} - {% if as_timestamp(event.start) | timestamp_custom('%d%m%y') != as_timestamp(event.end) | timestamp_custom('%d%m%y') %}{{ days[(as_timestamp(event.end) | timestamp_custom('%w') | int)-1][:3] }}{% endif %} {{as_timestamp(event.end) | timestamp_custom('%H:%M') }}: {{ event.summary }}
                {% endif -%}
              {% endfor -%}
            {% else %}
              #Ingenting
            {% endif -%}
          font: ../../media/Abel-Regular.ttf
          start_y: >
            {{ gap_header + 1.5 * gap_title + 1 * gap_line + gap_days + ((count0
            + 1 ) * gap_text)}}
          offset_y: 16
          delimiter: "#"
          size: 16
          x: 140
          color: black
        - type: text
          visible: "{{true if (count0+count1+count2) < 9 else false}}"
          value: >-
            {{ days[(today_at('00:00')+ timedelta(days=2)).weekday()] }} {{
            (today_at('00:00') + timedelta(days=2)).day }}. {{
            months[(today_at('00:00')+ timedelta(days=2)).month-1] }} 
          font: ../../media/Bungee.ttf
          x: 140
          "y": >
            {{ gap_header + 2 * gap_title + 4 * gap_line + gap_days + +
            (((count0 + 1) + (count1 + 1)) * gap_text)}}
          size: 16
          color: black
        - type: multiline
          value: |
            {% if events_day2 | count > 0 %}
              {% for event in (events_day2 | sort(attribute='start') | list) -%} 
                {% if as_timestamp(event.start) | timestamp_custom('%H:%M') == "00:00"%}
                  #Ganztägig - {{ event.summary }}
                {% else %}
                  #{% if as_timestamp(event.start) | timestamp_custom('%d%m%y') != as_timestamp(event.end) | timestamp_custom('%d%m%y') %}{{ days[(as_timestamp(event.start) | timestamp_custom('%w') | int)-1][:3] }} {% endif %}{{as_timestamp(event.start) | timestamp_custom('%H:%M') }} - {% if as_timestamp(event.start) | timestamp_custom('%d%m%y') != as_timestamp(event.end) | timestamp_custom('%d%m%y') %}{{ days[(as_timestamp(event.end) | timestamp_custom('%w') | int)-1][:3] }}{% endif %} {{as_timestamp(event.end) | timestamp_custom('%H:%M') }}: {{ event.summary }}
                {% endif -%}
              {% endfor -%}
            {% else %}
              #Ingenting
            {% endif -%}
          font: ../../media/Abel-Regular.ttf
          start_y: >
            {{ gap_header + 3 * gap_title + 1 * gap_line + gap_days + (((count0
            + 1) + (count1 + 1)) * gap_text)}}
          offset_y: 16
          delimiter: "#"
          size: 16
          x: 140
          color: black
          visible: "{{true if (count0+count1+count2) < 9 else false}}"
        - type: text
          visible: "{{true if (count0+count1+count2+count3) < 7 else false}}"
          value: >-
            {{ days[(today_at('00:00') + timedelta(days=3)).weekday()] }} {{
            (today_at('00:00') + timedelta(days=3)).day }}. {{
            months[(today_at('00:00')+ timedelta(days=3)).month-1] }} 
          font: ../../media/Bungee.ttf
          x: 140
          "y": >
            {{ gap_header + 3 * gap_title + 4 * gap_line + gap_days + +
            (((count0 + 1) + (count1 + 1) + (count2 + 1)) * gap_text)}}
          size: 16
          color: black
        - type: multiline
          value: |
            {% if events_day3 | count > 0 %}
              {% for event in (events_day3 | sort(attribute='start') | list) -%} 
                {% if as_timestamp(event.start) | timestamp_custom('%H:%M') == "00:00"%}
                  #Ganztägig - {{ event.summary }}
                {% else %}
                  #{% if as_timestamp(event.start) | timestamp_custom('%d%m%y') != as_timestamp(event.end) | timestamp_custom('%d%m%y') %}{{ days[(as_timestamp(event.start) | timestamp_custom('%w') | int)-1][:3] }} {% endif %}{{as_timestamp(event.start) | timestamp_custom('%H:%M') }} - {% if as_timestamp(event.start) | timestamp_custom('%d%m%y') != as_timestamp(event.end) | timestamp_custom('%d%m%y') %}{{ days[(as_timestamp(event.end) | timestamp_custom('%w') | int)-1][:3] }}{% endif %} {{as_timestamp(event.end) | timestamp_custom('%H:%M') }}: {{ event.summary }}
                {% endif -%}
              {% endfor -%}
            {% else %}
              #Ingenting
            {% endif -%}
          font: ../../media/Abel-Regular.ttf
          start_y: >
            {{ gap_header + 4 * gap_title + 1 * gap_line + gap_days + (((count0
            + 1) + (count1 + 1) + (count2 + 1)) * gap_text)}}
          offset_y: 16
          delimiter: "#"
          size: 16
          x: 140
          visible: "{{true if (count0+count1+count2+count3) < 7 else false}}"
          color: black
    target:
      device_id: xxxxxxxxxxxxxxxxxx
    action: open_epaper_link.drawcustom
mode: restart
